Class {
	#name : #CPreprocModel,
	#superclass : #MooseModel,
	#category : #'Famix-CPreproc-Entities-Model'
}

{ #category : #accessing }
CPreprocModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : #meta }
CPreprocModel class >> annotation [
	<FMClass: #CPreprocModel super: #MooseModel>
	<package: #'Famix-CPreproc-Entities'>
	<generated>
]
