Class {
	#name : #CPreprocPreprocDefine,
	#superclass : #CPreprocPreprocStatement,
	#traits : 'FamixTNamedEntity',
	#classTraits : 'FamixTNamedEntity classTrait',
	#category : #'Famix-CPreproc-Entities-Entities'
}

{ #category : #meta }
CPreprocPreprocDefine class >> annotation [

	<FMClass: #PreprocDefine super: #CPreprocPreprocStatement>
	<package: #'Famix-CPreproc-Entities'>
	<generated>
	^self
]
