Class {
	#name : #FamixCPreprocPreprocDefine,
	#superclass : #FamixCPreprocPreprocStatement,
	#traits : 'FamixTNamedEntity',
	#classTraits : 'FamixTNamedEntity classTrait',
	#category : #'Famix-CPreproc-Entities-Entities'
}

{ #category : #meta }
FamixCPreprocPreprocDefine class >> annotation [

	<FMClass: #PreprocDefine super: #FamixCPreprocPreprocStatement>
	<package: #'Famix-CPreproc-Entities'>
	<generated>
	^self
]
