Class {
	#name : #FamixCPreprocPreprocessorDefine,
	#superclass : #FamixCPreprocPreprocessorStatement,
	#traits : 'FamixTNamedEntity',
	#classTraits : 'FamixTNamedEntity classTrait',
	#category : #'Famix-CPreproc-Entities-Entities'
}

{ #category : #meta }
FamixCPreprocPreprocessorDefine class >> annotation [

	<FMClass: #PreprocessorDefine super: #FamixCPreprocPreprocessorStatement>
	<package: #'Famix-CPreproc-Entities'>
	<generated>
	^ self
]
