Class {
	#name : #FamixCppSourceTextAnchor,
	#superclass : #FamixCppSourceAnchor,
	#traits : 'FamixTHasImmediateSource',
	#classTraits : 'FamixTHasImmediateSource classTrait',
	#category : #'Famix-Cpp-Entities-Entities'
}

{ #category : #meta }
FamixCppSourceTextAnchor class >> annotation [

	<FMClass: #SourceTextAnchor super: #FamixCppSourceAnchor>
	<package: #'Famix-Cpp-Entities'>
	<generated>
	^self
]
