Extension { #name : 'FamixCStructuredType' }

{ #category : '*Famix-Cpp-Entities' }
FamixCStructuredType >> isClass [

	<generated>
	^ false
]

{ #category : '*Famix-Cpp-Entities' }
FamixCStructuredType >> isParametricEntity [

	<generated>
	^ false
]

{ #category : '*Famix-Cpp-Entities' }
FamixCStructuredType >> isQueryable [

	<generated>
	^ false
]

{ #category : '*Famix-Cpp-Entities' }
FamixCStructuredType >> isType [

	<generated>
	^ false
]
