Class {
	#name : #FamixCppUnknownSourceLanguage,
	#superclass : #FamixCppSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-Cpp-Entities-Entities'
}

{ #category : #meta }
FamixCppUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixCppSourceLanguage>
	<package: #'Famix-Cpp-Entities'>
	<generated>
	^self
]
