Class {
	#name : #FamixCMultipleFileAnchor,
	#superclass : #FamixCSourceAnchor,
	#traits : 'FamixTMultipleFileAnchor',
	#classTraits : 'FamixTMultipleFileAnchor classTrait',
	#category : #'Famix-C-Entities-Entities'
}

{ #category : #meta }
FamixCMultipleFileAnchor class >> annotation [

	<FMClass: #MultipleFileAnchor super: #FamixCSourceAnchor>
	<package: #'Famix-C-Entities'>
	<generated>
	^ self
]
