Class {
	#name : #FamixCRelativeSourceAnchor,
	#superclass : #FamixCEntity,
	#traits : 'FamixTRelativeSourceAnchor',
	#classTraits : 'FamixTRelativeSourceAnchor classTrait',
	#category : #'Famix-C-Entities-Entities'
}

{ #category : #meta }
FamixCRelativeSourceAnchor class >> annotation [

	<FMClass: #RelativeSourceAnchor super: #FamixCEntity>
	<package: #'Famix-C-Entities'>
	<generated>
	^ self
]
