Class {
	#name : #FamixCDereferencedInvocation,
	#superclass : #FamixCInvocation,
	#traits : 'FamixTDereferencedInvocation',
	#classTraits : 'FamixTDereferencedInvocation classTrait',
	#category : #'Famix-C-Entities-Entities'
}

{ #category : #meta }
FamixCDereferencedInvocation class >> annotation [

	<FMClass: #DereferencedInvocation super: #FamixCInvocation>
	<package: #'Famix-C-Entities'>
	<generated>
	^self
]
