Class {
	#name : #FamixCUnknownSourceLanguage,
	#superclass : #FamixCSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'Famix-C-Entities-Entities'
}

{ #category : #meta }
FamixCUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FamixCSourceLanguage>
	<package: #'Famix-C-Entities'>
	<generated>
	^self
]
