Class {
	#name : #FamixCMultipleFileanchor,
	#superclass : #FamixCSourceAnchor,
	#traits : 'FamixTMultipleFileAnchor',
	#classTraits : 'FamixTMultipleFileAnchor classTrait',
	#category : #'Famix-C-Entities-Entities'
}

{ #category : #meta }
FamixCMultipleFileanchor class >> annotation [

	<FMClass: #MultipleFileanchor super: #FamixCSourceAnchor>
	<package: #'Famix-C-Entities'>
	<generated>
	^self
]
