Class {
	#name : #FamixCIndexedFileAnchor,
	#superclass : #FamixCSourceAnchor,
	#traits : 'FamixTIndexedFileNavigation',
	#classTraits : 'FamixTIndexedFileNavigation classTrait',
	#category : #'Famix-C-Entities-Entities'
}

{ #category : #meta }
FamixCIndexedFileAnchor class >> annotation [

	<FMClass: #IndexedFileAnchor super: #FamixCSourceAnchor>
	<package: #'Famix-C-Entities'>
	<generated>
	^self
]
