Extension { #name : 'FamixCPreprocEntity' }

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isAccess [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isAssociation [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isAttribute [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isBehavioural [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isComment [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isEnumValue [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isFileAnchor [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isFunction [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isInvocation [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isLocalVariable [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isNamedEntity [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isPrimitiveType [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isReference [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isStructuralEntity [

	<generated>
	^ false
]

{ #category : '*Famix-C-Entities' }
FamixCPreprocEntity >> isType [

	<generated>
	^ false
]
