Class {
	#name : 'FamixPreprocModel',
	#superclass : 'MooseModel',
	#category : 'Famix-Preproc-Traits-Model',
	#package : 'Famix-Preproc-Traits',
	#tag : 'Model'
}

{ #category : 'accessing' }
FamixPreprocModel class >> allSubmetamodelsPackagesNames [
	<generated>
	^ #(#'Moose-Query' #'Famix-Traits')
]

{ #category : 'meta' }
FamixPreprocModel class >> annotation [
	<FMClass: #FamixPreprocModel super: #MooseModel>
	<package: #'Famix-Preproc-Traits'>
	<generated>
]
